sudo: required
dist: trusty
language: cpp

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

env:
  - BUILD_MODE=debug
  - BUILD_MODE=release

# Qt-5.5 doesn't build on MacOsX-10.9_x86_64 with GCC-4.8
matrix:
    exclude:
        - os: osx
          compiler: gcc

install:
    - source ci-scripts/travis-install.env

script:
    - source ci-scripts/travis-script.env

after_success:
    - source ci-scripts/travis-after-success.env
