sudo: required
dist: trusty
language: cpp

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

env:
  - BUILD_MODE=debug
  - BUILD_MODE=release

# Qt-5.5 doesn't build on MacOsX-10.9_x86_64 with GCC-4.8
matrix:
    exclude:
        - os: osx
          compiler: gcc

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "clang++" ]; then export MKSPEC=linux-clang; fi
    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "g++" ]; then export MKSPEC=linux-g++; fi

    - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "clang++" ]; then export MKSPEC=macx-clang; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "g++" ]; then export MKSPEC=macx-g++; fi

    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get -y update -qq && sudo apt-get -y install qt5-default; fi

    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install qt5; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=$(brew --prefix)/opt/qt5/bin:$PATH; fi

    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "g++" -a "${BUILD_MODE}" = "debug" ]; then sudo apt-get install lcov -y && sudo pip install cpp-coveralls; fi

script:
    - env
    - echo "Building for ${MKSPEC} in ${BUILD_MODE} mode..."
    - mkdir build
    - cd build
    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "g++" -a "${BUILD_MODE}" = "debug" ]; then qmake .. -spec ${MKSPEC} CONFIG+=${BUILD_MODE} "QMAKE_CXXFLAGS+=--coverage" "QMAKE_LFLAGS+=--coverage"; else qmake .. -spec ${MKSPEC} CONFIG+=${BUILD_MODE}; fi
    - make -j3 -k
    - QT_LOGGING_CONF='*=false' make check TESTARGS='-o $(QMAKE_TARGET).xml,xunitxml'
    - file app/qtslim
    # - ./app/qtslim --version

after_success:
    - pwd
    - find . -name '*.gc*'
    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "g++" -a "${BUILD_MODE}" = "debug" ]; then cpp-coveralls --verbose --root .. -E '.*/(build|tests|fitnesse|app)/.*'; fi
