version: CI/AppVeyor/{branch}.{build}

environment:
    QTDIR: C:\Qt\5.4\mingw491_32

build_script:
    - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw491_32\bin;%PATH%
    - set PATH="C:\Program Files\7-Zip";%PATH%
    - set
    - sh.exe --login ci-scripts/appveyor-build.sh
